routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
}); */

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::Post('/getsiteid', 'SitesController@getSiteId')->name('getSiteId');
Route::Post('/webhook', 'SitesController@webhook')->name('webhook');
Route::get('/pulling/{siteid}', 'externalSettings@pulling')->name('pulling');
Route::get('/addinguser/{siteid}', 'externalSettings@addinguser')->name('addinguser');
Route::Post('/createtask', 'SitesController@createTask')->name('createTask');

Route::get('/seeder', 'CreateSeeder@index');
Route::get('/impersonate/{site}', 'SitesController@setImpersonate');

Route::resource('sites', 'SitesController');

Route::get('/users', 'UsersController@index')->name('users.index');

Route::get('/test', 'SitesController@test')->name('test');

Route::get('settings', 'SettingsController@setting')->name('settings.setting');
Route::post('settings/saveHost', 'SettingsController@saveSettings')->name('settings.saveHost');
Route::get('settings/{host}', 'externalSettings@getSetting');

resources/views/admin/settings.blade.php
@extends('layouts.app')

@section('extra')


@endsection

@section('content')



<div class="container-fluid">
	<div class="card-box">
		<div class="row">
				<div class="col-sm-12">
					<h4 class="page-title">Settings</h4>
				</div>
		</div>
		@if (\Session::has('success'))
		<div class="row">
				<div class="col-sm-12 m-t-15">
				<div class="alert alert-success">
					{!! \Session::get('success') !!}
				</div>
				</div>
		</div>
		@endif
		<div class="row">
				<div class="col-sm-6 m-t-15">	
					
						<form method="post" action="{{ route("settings.saveHost") }}">
							{{ csrf_field() }}
							<div class="form-group">
								<label for="type">Host:</label>
								<select class="form-control" name="type" id="type">
									<option value="git" selected>Git</option>
								</select>
							</div>
							<div class="form-group">
								<label for="user">User:</label>
								<input type="text" class="form-control" name="user" id="user" value="{!! !empty($savedsettings['user'])?$savedsettings['user']:'' !!}">
							</div>
							<div class="form-group">
								<label for="email">Email:</label>
								<input type="text" class="form-control" name="email" id="email" value="{!! !empty($savedsettings['email'])?$savedsettings['email']:'' !!}">
							</div>
							<div class="form-group">
								<label for="org">Org:</label>
								<input type="text" class="form-control" name="org" id="org" value="{!! !empty($savedsettings['org'])?$savedsettings['org']:'' !!}">
							</div>
							<div class="form-group">
								<label for="token">Token:</label>
								<input type="text" class="form-control" name="token" id="token" value="{!! !empty($savedsettings['token'])?$savedsettings['token']:'' !!}">
							</div>
							<div class="form-group">
								<label for="token">Hubspot Api Key:</label>
								<input type="text" class="form-control" name="hubspot_api_key" id="hubspot_api_key" value="{!! !empty($savedsettings['hubspot_api_key'])?$savedsettings['hubspot_api_key']:'' !!}">
							</div>
							<button type="submit" class="btn btn-default">Update</button>
							<input type="hidden" name="settingType" value="host">
						</form>
					
				</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/sites.blade.php
@extends('layouts.app')

@section('extra')

<link href="{{ asset('assets/plugins/datatables/dataTables.colVis.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ asset('assets/plugins/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ asset('assets/plugins/datatables/fixedColumns.dataTables.min.css') }}" rel="stylesheet" type="text/css"/>
<style>
.buttons{
	display: none;
    padding: 0;
    margin: 0;
}
.buttons li{
	display: inline-block;
    margin-right: 10px;
    font-size: 13px;
    padding-left: 10px;
    border-left: 1px solid #cccccc;
    line-height: 1;
}
.buttons li:first-child{
	border:0;
	padding:0;
}
.table tr:hover .buttons{
	display:block;
}
#progress_report{
	background: #000;
    color: #ffffff;
    padding: 10px 20px;
	display:none;
}
</style>

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<div class="btn-group pull-right">
					<button class="btn btn-default waves-effect waves-light btn-sm pull-right" data-toggle="modal" data-target="#con-close-modal">Add New Site</button>
				</div>
				<h4 class="page-title">All Sites</h4>
			</div>
			<div class="col-sm-12 m-t-15">
				<div class="card-box">
					<table id="datatable-buttons" class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>Title</th>
								<th>Url</th>
								<th>Created on</th>
							</tr>
						</thead>
						<tbody>
							@foreach (json_decode($sites) as $site)
							<tr>
								<td>
								{{ $site->site_title }}
								<ul class="buttons">
									<li><a href="">View</a></li>
									<li><a href="/impersonate/{{ $site->id }}" target="_blank">Edit</a></li>
									<li><a href="">Trash</a></li>
								</ul>
								</td>
								<td>{{ $site->dev_url }}</td>
								<td>Published<br />{{ $site->created_at }}</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
    </div>
</div>

<div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title">Create New Site</h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<form method="POST" id="createpageform" action="">
					{{ csrf_field() }}
					<div class="col-md-12">
						<div class="form-group">
							<label for="field-1" class="control-label">Site Title</label>
							<input type="text" name="site_title" class="form-control" id="field-1" placeholder="" required>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label for="field-2" class="control-label">User</label>
							<select class="form-control" name="user_id" id="sel1">
								@foreach (json_decode($users) as $user)
									<option value="{{ $user->id }}">{{ $user->name }}</option>
								@endforeach
							</select>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label for="field-2" class="control-label" style="display:block;">Dashboard</label>
							<input type="text" name="dev_url" class="form-control" id="field-2" placeholder="" style="max-width: 100px;display: inline-block;">.frezit.com
						</div>
					</div>
					<!--<input type="submit" value="submit"> -->
					</form>
				</div>
				<div class="prog">
					<form id="secondstep">
					{{ csrf_field() }}
					</form>
					<div id="progress_report">

					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
				<button type="button" id="save" class="btn btn-info waves-effect waves-light">Add Site</button>
			</div>
		</div>
	</div>
</div><!-- /.modal -->
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/jszip.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.fixedHeader.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.keyTable.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/responsive.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.scroller.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.colVis.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.fixedColumns.min.js') }}"></script>
<script src="{{ asset('assets/pages/datatables.init.js') }}"></script>
<script>
$(document).ready(function(){
	$('#save').on('click', function(){
		btn = $(this);
		btn.prop('disabled', true);
		$('#progress_report').html();
		$('#progress_report').show();
		$('#progress_report').append('<p>Please wait while we are creating your site.</p>');
		$('#createpageform input[type="text"]').removeClass('parsley-error');
		$.ajax({
            type: "POST",
            url: '{{URL::route('sites.store')}}',
            data: $("#createpageform").serialize(),
            success: function( msg ) {
				var obj = jQuery.parseJSON(msg);
                if(obj.result.status == 'success'){
					$('#progress_report').append('<p>'+obj.result.message+'</p>');
					setTimeout(function(){ $('#progress_report').append('<p>Merging with Repository...</p>'); }, 300);
					$.ajax({
						type: "POST",
						url: '{{URL::route('webhook')}}',
						data: $("#secondstep").serialize(),
						success: function( msg ) {
							var obj = jQuery.parseJSON(msg);
							if(obj.uuid){
								$('#progress_report').append('<p>Successfully Merged.</p>');
								$.ajax({
									type: "POST",
									url: '{{URL::route('getSiteId')}}',
									data: $("#secondstep").serialize(),
									success: function( msg ) {
											var siteid = msg;
											$.ajax({
												type: "POST",
												url: '{{URL::route('createTask')}}',
												data: $("#secondstep").serialize()+'&siteid='+siteid,
												success: function( msg ) {
													if(msg=='success'){
													$('#progress_report').append('<p>Task generated for #Site '+siteid+'. Will take 5-15min to prepare your Dashboard</p>');
													setTimeout(function(){ window.location.href = "{{URL::route('sites.index')}}"; }, 3000);
													}
												}
											});
									}
								});


								//$('#progress_report').append('<p>Successfully Merged.</p>');
								//setTimeout(function(){ window.location.href = "{{URL::route('sites.index')}}"; }, 3000);
							}else{
								$('#progress_report').append('<p>'+msg+'</p>');
							}
						}
					});
					//window.location.href = "{{URL::route('sites.index')}}";
				}else if(obj.result.status == 'fail'){
					$('#progress_report').append('<p>'+obj.result.message+'</p>');
				}else{
					btn.prop('disabled', false);
					var obj = jQuery.parseJSON(msg);
					if(obj.error.length>0){
						for(var i = 0; i<obj.error.length; i++){
							$('input[name="'+obj.error[i].field+'"]').addClass('parsley-error');
						}
					}
				}
            }
        });
	})
	TableManageButtons.init();
})
</script>

@endsection

resources/views/admin/users.blade.php
@extends('layouts.app')

@section('extra')

<link href="{{ asset('assets/plugins/datatables/dataTables.colVis.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ asset('assets/plugins/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ asset('assets/plugins/datatables/fixedColumns.dataTables.min.css') }}" rel="stylesheet" type="text/css"/>
<style>
.buttons{
	display: none;
    padding: 0;
    margin: 0;
}
.buttons li{
	display: inline-block;
    margin-right: 10px;
    font-size: 13px;
    padding-left: 10px;
    border-left: 1px solid #cccccc;
    line-height: 1;
}
.buttons li:first-child{
	border:0;
	padding:0;
}
.table tr:hover .buttons{
	display:block;
}
</style>

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<div class="btn-group pull-right">
					<button class="btn btn-default waves-effect waves-light btn-sm pull-right" data-toggle="modal" data-target="#con-close-modal">Add New User</button>
				</div>
				<h4 class="page-title">All Users</h4>
			</div>
			<div class="col-sm-12 m-t-15">	
				<div class="card-box">
					<table id="datatable-buttons" class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>ID</th>
								<th>Name</th>
								<th>Email</th>
							</tr>
						</thead>
						<tbody>
							@foreach (json_decode($users) as $user)
							<tr>
								<td>
								{{ $user->id }}
								</td>
								<td>{{ $user->name }}</td>
								<td>{{ $user->email }}</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
    </div>
</div>

<div id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
	<div class="modal-dialog"> 
		<div class="modal-content"> 
			<div class="modal-header"> 
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> 
				<h4 class="modal-title">Create New User</h4> 
			</div> 
			<div class="modal-body"> 
				<div class="row"> 
					<div class="col-sm-12"> 
					<form id="createuserform" class="form-horizontal" method="POST" action="{{ route('register') }}">
						{{ csrf_field() }}
						<div class="form-group"> 
							<div class="col-xs-12">
								<select class="form-control" name="role" id="sel1">
									<option value="admin">Admin</option>
									<option value="site-admin">Site Admin</option>
									<option value="site-subscriber">Site Subscriber</option>
								</select>
							</div>
						</div>
						<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
							<div class="col-xs-12">
								<input id="name" type="text" class="form-control" name="name" placeholder="Name" value="{{ old('name') }}" required>
							</div>
						</div>

						<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
							<div class="col-xs-12">
								<input id="email" type="email" class="form-control" name="email" placeholder="Email" value="{{ old('email') }}" required>
							</div>
						</div>

						<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
							<div class="col-xs-12">
								<input id="password" type="password" placeholder="Password" class="form-control" name="password" required>
							</div>
						</div>
						<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
							<div class="col-xs-12">
								<input id="password-confirm" type="password" class="form-control" name="password_confirmation" placeholder="Confirm Password" required>
							</div>
						</div>
					</form>
					</div>
				</div> 
			</div> 
			<div class="modal-footer"> 
				<button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button> 
				<button type="button" id="save" class="btn btn-info waves-effect waves-light">Add User</button> 
			</div> 
		</div> 
	</div>
</div><!-- /.modal -->
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/buttons.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/jszip.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.fixedHeader.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.keyTable.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/responsive.bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.scroller.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.colVis.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.fixedColumns.min.js') }}"></script>
<script src="{{ asset('assets/pages/datatables.init.js') }}"></script>
<script>
$(document).ready(function(){
	$('#save').on('click', function(){
		$('#createuserform input[type="text"]').removeClass('parsley-error');
		$('#createuserform .error').remove();
		$.ajax({
            type: "POST",
            url: "{{ route('register') }}",
            data: $("#createuserform").serialize(),
            success: function( msg ) {
				if(msg.errors){
					$.each(msg.errors,function(k,value){
                        $('input[name="'+k+'"]').addClass('parsley-error');
						$('input[name="'+k+'"]').parents('.col-xs-12').append('<span class="error">'+value+'</span>');
                    });
				}else{
					$('#createuserform').prepend('<div class="alert alert-success"><strong>Success!</strong> User Successfully created. Redirecting...</div>');
					setTimeout(function(){ window.location.href = "{{URL::route('users.index')}}"; }, 5000);
				}
            }
        });
	})
	TableManageButtons.init();
})
</script>

@endsection